name: "Setup Rust Environment"
description: "Install Rust, mold linker (Linux), and cache dependencies"

inputs:
  rust-toolchain:
    description: "Rust toolchain to install"
    required: false
    default: "stable"
  targets:
    description: "Additional Rust targets to install"
    required: false
    default: ""
  components:
    description: "Additional Rust components to install"
    required: false
    default: ""
  cache-key:
    description: "Rust cache key suffix"
    required: false
    default: ""
  workspaces:
    description: 'Workspace paths for caching (format: "path -> target")'
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}

    - name: Install mold linker (Linux only)
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y mold

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.cache-key }}
        workspaces: ${{ inputs.workspaces }}
        cache-on-failure: true
