name: "CytoScnPy"
description: "High-performance dead code elimination analysis tool for Python."
author: "djinn09"
branding:
  icon: "search"
  color: "green"

inputs:
  path:
    description: "Path(s) to analyze"
    required: false
    default: "."
  args:
    description: "Additional arguments for cytoscnpy (e.g., --secrets --danger --quality)"
    required: false
    default: ""
  version:
    description: "Version of cytoscnpy to install"
    required: false
    default: "latest"
  python-version:
    description: "Version of Python to set up"
    required: false
    default: "3.x"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install CytoScnPy
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        if [ "$VERSION" == "latest" ]; then
          pip install cytoscnpy
        else
          pip install "cytoscnpy==$VERSION"
        fi

    - name: Run CytoScnPy
      shell: bash
      env:
        CYTO_PATH: ${{ inputs.path }}
        CYTO_ARGS: ${{ inputs.args }}
      run: |
        cytoscnpy "$CYTO_PATH" $CYTO_ARGS
